version: '3'
services:   
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "9001:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mariadb
        container_name: mariadb
        restart: always        
        environment:
            - MYSQL_DATABASE=app
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
        ports:
            - "3306:3306"
